FROM microsoft/aspnetcore

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 5000

# Start the app
ENTRYPOINT ["dotnet", "Djohnnie.HomeAutomation.Web.dll"]