FROM microsoft/aspnetcore

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 8888

ENV TZ=Europe/Brussels
ENV SMAPPEE_CLIENT_ID=...
ENV SMAPPEE_CLIENT_SECRET=...
ENV SMAPPEE_USERNAME=...
ENV SMAPPEE_PASSWORD=...
ENV NEST_TOKEN=...
ENV NEST_THERMOSTAT=...

# Start the app
ENTRYPOINT ["dotnet", "Djohnnie.HomeAutomation.Web.dll"]